name: Despliegue Ruben
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y Subir Imagen
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/libreria:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/libreria:latest

      - name: Desplegar en Debian Ruben
        run: |
          # Decodificar la clave privada
          echo "${{ secrets.SSH_KEY }}" | base64 -d > private_key.pem
          chmod 600 private_key.pem
          
          # Conectar y desplegar
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            docker stop ruben || true
            docker rm ruben || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/libreria:latest
            docker run -d -p 80:80 --name ruben ${{ secrets.DOCKER_USERNAME }}/libreria:latest
          "
